[phases.setup]

[phases.install]
cmds = [
  'apt-get update',
  'apt-get install -y tesseract-ocr libtesseract-dev',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['tesseract --version']

[start]
cmd = 'uvicorn api_server:app --host 0.0.0.0 --port $PORT'
